name: wan
channels:
    # You can use the TUNA mirror to speed up the installation if you are in mainland China.
    # - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
    - pytorch
    - defaults
    - conda-forge
    # - nvidia
    - pyg
    - pytorch3d
dependencies:
    - python>=3.6
    # common used
    - pip
    - matplotlib
    - jupyterlab
    - pyyaml
    - tqdm
    - imageio
    - pytorch >= 2.0.0
    - torchvision
    - pytorch-cuda
    #    - pytorch3d
    - pyg # torch_geometric
    -   pip:
            # torch
            #   - torch >= 2.0.0
            #   - torchvision
            #   - torchaudio
            # common
            - json_tricks
            - pycocotools
            - opencv-python # <= 4.1.1.26 # to avoid Error: Cannot move to target thread
            - psutil
            - shutils
            - h5py
            - rich
            - gpustat
            - pytest
            - yapf
            - dearpygui
            - einops
            - open3d >= 0.15.2
            - trimesh[all]
            - transforms3d
            #            - plyfile
            - kornia
            - imageio-ffmpeg
